### ISSUE TITLE
asText broken for slices with document links

### ISSUE THREAD

**Issue by aeirola** [prismicio/javascript-kit#104]
`SliceZone.asText()` breaks if the slice zone contains any document links. The problem is that it doesn't take a `linkResolver` as an argument, and thus does not pass one to nested fragments.

It seems as if `Slice.asText()` would also to be updated to pass the `linkResolver` to the nested fragment.

I can create a pull-request to fix this if needed.

**Comment by erwan** [comment]
Hi @aeirola ,

Yes, a PR would be great! If you can also include a test, that would be even better ;)
