### ISSUE TITLE
api.previewSession syntax error

### ISSUE THREAD

**Issue by ds300** [prismicio/javascript-kit#106]
At least I think this is a syntax error... [`previewSession`](https://github.com/prismicio/javascript-kit/blob/37c0d394376f3a3b1198fcbc24714a2b7d9341b8/lib/api.js#L364) binds a variable `api` and later refers to a `self` variable which, AFAICT, is supposed to be the same thing but has not been bound anywhere. This confuses me because no syntax errors are thrown when I use `previewSession`, but it doesn't work properly (the callback is never invoked/promise is never resolved). If I [consolidate the bindings](https://github.com/ds300/javascript-kit/blob/master/lib/api.js#L364) things work as expected.

I can submit a PR if you like.

**Comment by erwan** [comment]
thank you for the report, I'll fix it.

**Comment by erwan** [comment]
fixed in 2.1.1

**Comment by ds300** [comment]
Thanks for the quick fix! :+1:
