### ISSUE TITLE
console.log(Prismic) is empty

### ISSUE THREAD

**Issue by jsmankoo** [prismicio/javascript-kit#107]
var Prismic = require('prismic.io');

the above mentioned statement when console.log'd in node.js works just fine.
But in browserify returns an empty object

**Comment by erwan** [comment]
What version did you use?

I noticed an issue with browserify, that I fixed in version 2.1.2.

Latest version is now 2.1.3.

**Comment by jsmankoo** [comment]
yup
seems good now
