### ISSUE TITLE
Invalid requests to npmcdn.com

### ISSUE THREAD

**Issue by mjackson** [prismicio/javascript-kit#114]
I've noticed a lot of invalid requests for the `prismic.io` package coming through npmcdn.com in the form:

    /prismic.io@2.0.0-beta2/dist/prismic.io.min.js?_=1463446463553

The reason these requests are invalid is because the query string is designed to bust the cache. However, by busting the cache these requests bypass the CDN and put unnecessary strain on the origin server.

I looked through your docs but I couldn't find where you're telling people to use these URLs, so I'm not sure where they're coming from (I can't see referrers from CDN traffic), but I thought you guys might have a page somewhere that generates those URLs. If so, would you please fix it? Thanks!

**Comment by erwan** [comment]
Hi,

I don't think we advertised URLs with a cache breaker anywhere, so I can only assume one of our users have a framework that adds it automatically.

The only place we're suggesting to use the CDN is on the README: https://github.com/prismicio/javascript-kit

Sorry our users are being uncivil, if there's anything we can do to help let me know. You have absolutely no way to figure out who the referrer is? Maybe the CDN provides some logs?

**Comment by mjackson** [comment]
Thanks for the reply, @erwan :) Unfortunately due to the volume of requests I get on the CDN it makes it difficult for them to make detailed analytics available, but I'll keep trying.
