### ISSUE TITLE
Async example does not work

### ISSUE THREAD

**Issue by henryoswald** [prismicio/javascript-kit#116]
We don't really like using promises and generally just use standard async code, the example in the readme.md doesn't seem to work, the api.query callback is never called.

**Comment by erwan** [comment]
Hi,

What version are you using? Can you post a full example reproducing the issue on gist or somewhere?

**Comment by henryoswald** [comment]
Hi, it is litterally a copy and paste from the readme example, i've added console.log for debugging

```

» cat prim.js
var Prismic = require('prismic.io');

Prismic.api("http://lesbonneschoses.prismic.io/api", function(error, api) {
  console.log("this is called")
  api.query("", function(error, response) { // An empty query will return all the documents
    console.log("never called")
    if (error) {
      console.log("Something went wrong: ", err);
    }
    console.log("Documents: ", response.documents);
  });
});
» node -v
v4.2.2
» node prim.js
this is called
»
```

**Comment by erwan** [comment]
OK, I'll try it when I get some time but it's a bit surprising because most of the tests are using callbacks:

https://github.com/prismicio/javascript-kit/blob/master/test/test.js#L67

**Comment by erwan** [comment]
I see, you're correct - the callback is in third position now and options in second. I've updated the README.
