### ISSUE TITLE
Document publicationDate properties invalid in Safari

### ISSUE THREAD

**Issue by udyux** [prismicio/javascript-kit#148]
In Safari (tested on 10.0.3), `firstPublicationDate` and `lastPublicationDate` properties are returned as `Invalid Date`. See [this StackOverflow question](http://stackoverflow.com/questions/4310953/invalid-date-in-safari) for a possible lead on fixing the issue.

I hoped a workaround could be parsing the string timestamp (`first_publication_date`) myself but it doesn't seem to be exposed on the response object.

Both properties work correctly in Chrome and Firefox.

**Comment by srenault** [comment]
We'll look at it ASAP. Thanks for reporting this.

**Comment by arnaudlewis** [comment]
Fixed in the latest release with this PR #151
