### ISSUE TITLE
Export `SimpleSlice` in fragments.js

### ISSUE THREAD

**Issue by TimonVS** [prismicio/javascript-kit#149]
All fragment types are being exported, except for `SimpleSlice` (https://github.com/prismicio/javascript-kit/blob/master/lib/fragments.js#L1398:L1420).
I need to extend `SimpleSlice` for a custom parser.

**Comment by arnaudlewis** [comment]
No problem @TimonVS, it will be available in the next version. It should be released in the next few days.
