### ISSUE TITLE
How to use Predicate with "OR" operator 

### ISSUE THREAD

**Issue by Fabiencdp** [prismicio/javascript-kit#161]
Hi, 

Here is a way to get document using some kind of "OR" operator ? 
for example something like: 

```
api.query([
    Prismic.Predicates.any('my.post.field1', [ someValues ]),
    Prismic.Predicates.or('my.post.field2', [ someOtherValue ])
]).then(function(response) {
    // ...
});
```
Thanks for your help

**Comment by Duaner** [comment]
Hello our api is not providing any OR operator. You might want to use to query for your use case. I will track this as a feature request anyway. Maybe get in touch with the support they will be able to help you structure your query to achieve what you're looking for.
