### ISSUE TITLE
submit() method should returns a Promise.

### ISSUE THREAD

**Issue by ggrossetie** [prismicio/javascript-kit#71]
I think it would be great if the `submit()` method returns a Promise.
In my case I need to query multiple documents to compose my page (the two latest news, the page content, a popular member, etc...) and my code is a callback hell !

``` javascript
ctx.api.form('everything').ref(ctx.ref).query('firstQuery').submit(function (err, docs) {
  if (err) { prismic.onPrismicError(err, req, res); return; }

  ctx.api.form('everything').ref(ctx.ref).query('secondQuery').submit(function (err, docs) {
    if (err) { prismic.onPrismicError(err, req, res); return; }

    ctx.api.form('everything').ref(ctx.ref).query('thirdQuery').submit(function (err, docs) {
        if (err) { prismic.onPrismicError(err, req, res); return; }
        res.render('', {});
    });
  });
});
```

But will look much better with Promise:

``` javascript
var firstQuery = ctx.api.form('everything').ref(ctx.ref).query('firstQuery').submit();
var secondQuery = ctx.api.form('everything').ref(ctx.ref).query('secondQuery').submit();
var thirdQuery = ctx.api.form('everything').ref(ctx.ref).query('thirdQuery').submit();

firstQuery.then(secondQuery).then(thirdQuery).then(new function(result) {
  res.render('', {});
});
```

Maybe I'm missing something with the API ? Or my use case is an edge case ?

Thanks, and great product by the way (a pleasure to develop a website with :+1:)

**Comment by azappa** [comment]
Any chance (or tutorial) to integrate Prismic with KoaJS (or generators, using --harmony)?

**Comment by erwan** [comment]
Hi azappa,

We only provide starter kit for the most popular frameworks, which is why for Node.js we have an Express.js starter: https://github.com/prismicio/javascript-nodejs-starter

That said the kit should work with any framework, if you have any problem to integrate it with KoaJS don't hesitate to reach us either though a support ticket or here.
