### ISSUE TITLE
Dealing with optional attribute

### ISSUE THREAD

**Issue by Mogztter** [prismicio/javascript-kit#78]
Hi,

I have some optional attributes in my document. I'm using Node.js/Express with `ejs` template:

``` javascript
document.get("page.catch_phrase").asText()
```

The problem is that I need to check that `document.get("page.catch_phrase") != null` before calling `asText()`. Something like:

``` javascript
<% if (document.get("page.catch_phrase") != null ) { %>
<%- document.get("page.catch_phrase").asText() %>
<% } %>
```

This is really verbose and I need to be extra careful because if I forget one of them my template will return a HTTP 500 :cry: 
Can we add a shortcut method to handle optional attribute ?

``` javascript
document.getAsText("page.catch_phrase") // corresponding text value or empty ""
```

Thanks

**Comment by mattfysh** [comment]
@erwan - any thoughts on this?

**Comment by erwan** [comment]
Hi @mattfysh ,

I'm no longer involved in this project, but @arnaudlewis will probably follow up from here ;)

**Comment by levimykel** [comment]
This issue is resolved by using the prismic.io API v2 with the [prismic-javascript](https://github.com/prismicio/prismic-javascript) and [prismic-dom](https://github.com/prismicio/prismic-dom) kits. We recommend updating to this setup to avoid this issue.
